// Sprites for the mysterious branch objects. 16×16 string grids, same grammar
// as sprites.ts: '.'=transparent X=tint x=dark-tint L=light-tint k=outline,
// fixed letters w(bone) r(red) y(gold) g(green) B(brown) S(steel) p(purple)
// o(orange) h(dark grey). Registered into the shared sprite atlas at load.
import { registerSprites } from './sprites';

registerSprites({
  // ossuary — a laden bone-shelf with one gap, exactly remains-shaped
  obj_niche: [
    'kkkkkkkkkkkkkkkk',
    'kXXXXXXXXXXXXXXk',
    'kXwwXwwwXXwwwXXk',
    'kXwwXwwwXXwwwXXk',
    'kkkkkkkkkkkkkkkk',
    'kXwwwXkhhhkXwwXk',
    'kXwwwXkhhhkXwwXk',
    'kXXXXXkhhhkXXXXk',
    'kkkkkkkhhhkkkkkk',
    'kXwwXXkhhhkwwwXk',
    'kXwwXXkhhhkwwwXk',
    'kXXXXXkkkkkXXXXk',
    'kkkkkkkkkkkkkkkk',
    'kXwwwwXXwwwwwXXk',
    'kXwwwwXXwwwwwXXk',
    'kkkkkkkkkkkkkkkk',
  ],
  // ossuary — the misfiled remains: a crowned skull atop loose bones
  obj_skull: [
    '................',
    '................',
    '......y.y.y.....',
    '.....kyyyyyk....',
    '.....kwwwwwk....',
    '....kwwwwwwwk...',
    '....kwwwwwwwk...',
    '....kwkwwkwwk...',
    '....kwkwwkwwk...',
    '....kwwwwwwwk...',
    '.....kwkwkwk....',
    '.....kwwwwwk....',
    '...kwwkkkkkww...',
    '..kwwwwkwwwwwk..',
    '.kwwkwwwwkwwwwk.',
    '..kkkkkkkkkkkk..',
  ],
  // waxgarden — a cold votive candle on a drowned stand of risen wax
  obj_candle: [
    '................',
    '.......k........',
    '......khk.......',
    '......kLk.......',
    '.....kXLXk......',
    '.....kXLXk......',
    '.....kXLXk......',
    '.....kXLXk......',
    '.....kXLXk......',
    '....kXXLXXk.....',
    '....kXXXXXk.....',
    '...kXXXXXXXk....',
    '..kxXXXXXXxxk...',
    '.kxxXXXXXXXxxk..',
    'kxxxxXXXXxxxxxk.',
    'kkkkkkkkkkkkkkk.',
  ],
  // waxgarden — the same candle, lit at last
  obj_candle_lit: [
    '.......o........',
    '......oyo.......',
    '......oyo.......',
    '.....oyyyo......',
    '.....kXLXk......',
    '.....kXLXk......',
    '.....kXLXk......',
    '.....kXLXk......',
    '.....kXLXk......',
    '....kXXLXXk.....',
    '....kXXXXXk.....',
    '...kXXXXXXXk....',
    '..kxXXXXXXxxk...',
    '.kxxXXXXXXXxxk..',
    'kxxxxXXXXxxxxxk.',
    'kkkkkkkkkkkkkkk.',
  ],
  // silkfen — the tithe-scale: two silk pans hung from a single thread
  obj_scale: [
    '.......k........',
    '.......k........',
    '..kkkkkkkkkkk...',
    '..k....k....k...',
    '..k....k....k...',
    '.kXk...k...kXk..',
    '.kXk...k...kXk..',
    'kXXXk..k..kXXXk.',
    'kwwwXk.k.kXXXXk.',
    '.kXXk..k..kXXk..',
    '..kk...k...kk...',
    '.......k........',
    '......kXk.......',
    '.....kXXXk......',
    '....kxXXXxk.....',
    '....kkkkkkk.....',
  ],
  // roots — a grave-elf cairn, one hand still holding the charred seed
  obj_cairn: [
    '................',
    '................',
    '................',
    '......kkk.......',
    '.....kXXXk......',
    '....kXXLXXk.....',
    '...kXxXXXxXk....',
    '...kXXkkkXXk....',
    '..kXxkhyhkxXk...',
    '..kXXkhkhkXXk...',
    '.kXxXwkkkwXxXk..',
    '.kXXXwwwwwXXXk..',
    'kXxXXXwwXXXXxXk.',
    'kXXxXXXXXXxXXXk.',
    'kxxXXxXXxXXXxxk.',
    'kkkkkkkkkkkkkkk.',
  ],
  // roots — the warm hollow, root-lined, exactly seed-shaped
  obj_hollow: [
    '................',
    '................',
    '....B.....B.....',
    '...BB..B..BB....',
    '..kBkkkBkkkBk...',
    '..kkxxxxxxxkk...',
    '.kBxkkkkkkxxBk..',
    '.kkxkhhhhkxxkk..',
    '.kBxkhoohhkxBk..',
    '.kkxkhoohhkxkk..',
    '.kBxkhhhhhkxBk..',
    '..kxxkkkkkxxk...',
    '..kBkxxxxxkBk...',
    '...kkBkkkBkk....',
    '....B..B..B.....',
    '................',
  ],
  // chains — a cell door of vault-iron bars
  obj_cell: [
    'kkkkkkkkkkkkkkkk',
    'kXXXXXXXXXXXXXXk',
    'kXkSkhSkhSkhSkXk',
    'kXkSkhSkhSkhSkXk',
    'kXkSkhSkhSkhSkXk',
    'kXkSkhSkhSkhSkXk',
    'kXXXXXXXXXXXXXXk',
    'kXkSkhSkhSkhSkXk',
    'kXkSkhSkhSkhSkXk',
    'kXkSyhSkhSkhSkXk',
    'kXkSkhSkhSkhSkXk',
    'kXkSkhSkhSkhSkXk',
    'kXkSkhSkhSkhSkXk',
    'kXXXXXXXXXXXXXXk',
    'kxxxxxxxxxxxxxxk',
    'kkkkkkkkkkkkkkkk',
  ],
  // chains — the reservation ledger, open on its stand
  obj_ledger: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kwwwwkwwwwwk..',
    '.kwwhwhkwhwhwwk.',
    '.kwwwwwkwwwwwwk.',
    '.kwhwhwkwhwrwwk.',
    'kwwwwwwkwwwwwwwk',
    'kkkkkkkkkkkkkkkk',
    '.....kxXXxk.....',
    '......kXXk......',
    '......kXXk......',
    '......kXXk......',
    '.....kxXXxk.....',
    '....kxXXXXxk....',
    '....kkkkkkkk....',
  ],
  // cistern — a basin of water that has not moved in nine generations
  obj_basin: [
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '..kkXXXXXXXXkk..',
    '.kXXkkkkkkkkXXk.',
    '.kXkLLLLLLLLkXk.',
    '.kXkLwLLLLwLkXk.',
    '.kXkLLLLLLLLkXk.',
    '..kXkkkkkkkkXk..',
    '...kXXXXXXXXk...',
    '....kxXXXXxk....',
    '.....kxXXxk.....',
    '....kxXXXXxk....',
    '...kxxXXXXxxk...',
    '...kkkkkkkkkk...',
  ],
});
